# Generated by Django 3.1.4 on 2020-12-26 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='contact',
            new_name='contactModel',
        ),
    ]
